//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiniela.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsers()
        {
            this.tblRole = new HashSet<tblRole>();
        }
    
        public int idUser { get; set; }
        public string vName { get; set; }
        public string vLastName { get; set; }
        public string vUserName { get; set; }
        public string vPassword { get; set; }
        public Nullable<bool> bActive { get; set; }
        public string vProfilePicture { get; set; }
        [NotMapped]
        [Compare("vPassword", ErrorMessage = "Las contraseñas no coinciden")]
        public string vConfirmPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRole> tblRole { get; set; }

    }
}
